version: '3.7'

services:
  nestjs:
    image: node:latest
    depends_on:
      - rabbitmq
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "yarn install && yarn run start:dev"
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:3.6.5-management
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq:rw
      - ./.docker/rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./.docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
