version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.6.5-management
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./.docker/rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./.docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro